### ISSUE TITLE
IoRing support for windows

### ISSUE THREAD

**Issue by zzwxh** [tokio-rs/mio#1697] opened 2023-07-26 21:51 UTC
IoRing is a new windows api.

**Comment by Thomasdezeeuw** [comment] 2023-07-27 09:57
Duplicate of https://github.com/tokio-rs/mio/issues/1591. Basically it's a maybe for Mio v2, otherwise you can look at https://github.com/Thomasdezeeuw/a10 which works on Linux currently.

**Closed by Thomasdezeeuw** 2023-07-27 09:57 UTC

**Comment by dlight** [comment] 2024-05-27 06:13
Note that [I/O ring](https://learn.microsoft.com/en-us/windows/win32/api/ioringapi/) is a Windows API, while io_uring is a Linux API. [A10](https://github.com/Thomasdezeeuw/a10) is a crate for Linux io_uring, not Windows I/O rings.

[Here is a comparison between the two APIs](https://windows-internals.com/ioring-vs-io_uring-a-comparison-of-windows-and-linux-implementations/).

**Comment by Thomasdezeeuw** [comment] 2024-05-27 08:16
I'll reopen, but it think the design is fairly similar between Windows' I/O ring and Linux's io_uring. Neither of which is compatible with Mio's current design.
