### ISSUE TITLE
Poll -  unexpected behavior

### ISSUE THREAD

**Issue by frehberg** [tokio-rs/mio#767] opened 2017-11-29 16:52 UTC
Hi 

I implemented a small test checking for timeouts
https://github.com/frehberg/mio/commit/ea90166c5a4fc2be4009258e4d628b09d119d76d

In line 248 of that patch the assertion fails. The queue is empty, and I would expect the Poll::poll() to block for 300msecs timeout, but the poll() returns immediatly. 
Seems to be an issue with the state of the readyness-queue, prepare_sleep()  forcing timeout to 0. 

I analyzed the code and added some comments 
https://github.com/frehberg/mio/commit/1ddf9a825873bd7f30ff87f347142fdc91e02d0f

Is this something anybody is working at? Otherwise I would try to create a patch.

**Comment by carllerche** [comment] 2017-12-15 22:39
Generally speaking, `Poll::poll` can wakeup for any reason. That said, minimizing the wakeups is good.

Could you provide a high level explanation of what you think the issue is?

> FIXME just used by consumer, no need to be marker-node

I'm not sure what this means.

> FIXME, missing guard, must not release_node of closed-marker and sleep-marker

It is not possible to get a `closed_marker` or `sleep_marker` at that point. That code path is only hit when a `closed_marker` has been observed, so we cannot be enqueuing it again. `sleep_marker` is never enqueued.

This should be a comment.

> FIXME use `while` instead of `if` to skip marker-sequence

Not sure why you think it should be a while. The markers are there to prevent iterating further.

> FIXME, closed-marker should be handled like hard end!

Not sure what this means specifically.

> FIXME, this is no inconsistency, just concurrent assignment of head, so tail->next having been modified. For consistency reasons exit and rerun!

Not sure what you mean here. the "inconsistent" terminology is what other impls of the mpsc queue have used. It just means "try again later".

**Comment by frehberg** [comment] 2017-12-20 20:09
First, I really admire the code of mio, it provides a very important feature, merging system events and custom events into a single event-queue. I think this is the central module to avoid fragmentation of all the network-libraries of Rust. 

Generally speaking, my feeling is that current implementation is using way too many markers in the queue-logic, causing too many possible combinations/sequences. 

Now I understand the code much better than I did when I added the first FIXME-comments, but still I would prefer to refactor the code reducing  the number of markers to two (including the closed-marker), simplifying the state machine and reasoning concerning emptiness and sleeping. 
 
Regarding the amount of markers and the if/while discussion in  the function dequeue, here in some situations the dequeue might dequeue another marker and return as event (AFAICS) After skipping one marker, one should check if the next node might be one more marker. (reducing amount of markers to 1+1 would simplify the reasoning here)

In addition,  the function prepare_for_sleep is performing 'strange' condition checks reasoning about emptiness, and in line https://github.com/carllerche/mio/blob/split-poll-and-register/src/poll.rs#L2041  it is assigning  sleep_marker.next  to null, although the sleep_marker might be enqueued that moment (?!), interrrupting the queue (AFAICS). Maybe, can you explain, why this it is safe to assign sleep_marker.next here?

And if system-events occur with high frequency and the Poll::poll-parameter of type sys::Events has little capacity, the custom events queue may be starved (Events-list is filled with system-events and no capacity is remaining for pending custom events)

With your help and support, I would like to put some effort into the code with the objectives 
* to simplify the logics/reasoning 
* dealing with system-customer events in a fair manner (eg round robin) 
* a way to balance system and custom events (or being able to tell quotient)

**Comment by carllerche** [comment] 2018-01-04 21:15
> Generally speaking, my feeling is that current implementation is using way too many markers in the queue-logic, causing too many possible combinations/sequences.

The code is not simple, but it has to handle a lot of edge cases. I would be happy to simplify, but it would have to be done very carefully and incrementally.

Re: resetting the next pointer. The sleep marker cannot be in the queue at that point. I added a comment explaining why in https://github.com/carllerche/mio/pull/794.

I'm happy to help, but it should be done very incrementally and carefully.

**Comment by Thomasdezeeuw** [comment] 2019-07-08 19:22
From reading the linked code this is about the custom readiness queue, which is gone, well sort of it's still used on Windows, but that needs to be rewritten, so I'm going to close this. @frehberg if anything still needs to be done for this please reopen.

**Closed by Thomasdezeeuw** 2019-07-08 19:22 UTC
