### ISSUE TITLE
Noob: Example: TCP: Client: Full error handling.

### ISSUE THREAD

**Issue by cheako** [tokio-rs/mio#1081] opened 2019-09-09 05:34 UTC
I tried some examples and playing around, but I'm still confused as to how I'm supposed to test for connection success.  I also don't know how to perform lookups(name to number and sometimes number to name is useful) for hosts or ports.  I don't clearly know where the split in functionality is for std and mio.

Looking for some full examples, projects using mio for Client TCP appreciated.

**Comment by cheako** [comment] 2019-09-09 10:41
Just got EPIPE on write().

**Comment by Thomasdezeeuw** [comment] 2019-09-09 11:45
Currently DNS lookups in stdlib are done synchronously by the [`ToSocketAddrs`](https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html) trait (the actual implementation uses libc). We can't use this in Mio since those lookups are blocking, so Mio only provides connecting using [socket addresses](https://doc.rust-lang.org/std/net/enum.SocketAddr.html) (ip & port). If you want to do DNS lookups you'll need to do it yourself, Mio won't provide this functionally (as it's not as easy as it might seem). But crates.io might provide some crates that do this: https://crates.io/search?q=dns.

A `TcpStream` is connected once you receive a [writable event](https://docs.rs/mio/0.6.19/mio/struct.Ready.html#method.is_writable) for the connection, which indicate the connection is ready for writing.

Generally though I would recommend looking at [Tokio](https://crates.io/crates/tokio), it's a higher level framework that does provide things like DNS and an easier to use API.

Also could expand on the `EPIPE` error? Your edit suggested it was an error on your end and not in the Mio code, but It's not quite clear.

**Comment by cheako** [comment] 2019-09-10 02:04
The EPIPE condition was a result of receiving a writable event when the locolhost port was in a closed state.  What I said was having an example that illustrates how to catch every possible condition would solve this problem, because receiving TCPRst is a likely result of sending TCPSyn.

**Comment by Thomasdezeeuw** [comment] 2019-09-10 09:43
The problem is that the errors are different on each platform and Mio make no attempt to "normalise" the errors. If you want to know about each possible error its best to read the OS manual, e.g. [`write(2)` on Linux](http://man7.org/linux/man-pages/man2/write.2.html).

**Comment by cheako** [comment] 2019-09-10 18:24
@Thomasdezeeuw That's fine, the example I'm talking about would then be filled with platform specific blocks.  What about projects that are multi-platform that use mio, they should be good enough examples?

**Comment by cheako** [comment] 2019-09-10 18:51
Confirmed, on Linux when connecting to 127.0.0.1 when the local port is in state closed a is writable event is sent and the resulting write() returns Broken Pipe.

**Comment by Thomasdezeeuw** [comment] 2019-09-11 09:03
Such an example would be helpful, but it would be very difficult to get right and to maintain it. First each OS (even Unixes) use different error (kind) for the same error, for example Windows uses `ConnectionAborted` when the reading side of the peer is closed where Unix uses `BrokenPipe` as you found out, see https://github.com/tokio-rs/mio/pull/1070/files#diff-57814c10624d570cd800ed65daf96825R344-R346. Next we have various system calls, e.g. `read(2)`, `write(2)`, etc., that all (can) return different errors depending on the OS. Handling all errors in an example would be very difficult to maintain properly and I'm not convinced we should do that in Mio.

In most cases you only need to check for a subset of the errors, e.g. `WouldBlock`, `Interrupted`, and see all other errors as terminal for the connection and just close the connection (log the error of course) and let the client try again.

**Comment by cheako** [comment] 2019-09-11 17:18
I understand what you are saying about different errors, because Linux has different behavior when connecting to localhost then it does when connecting to remote hosts.

I'm not saying the example has to be part of mio, but somewhere someone has to have an example, otherwise your saying no one has been able to use mio properly?

**Comment by Thomasdezeeuw** [comment] 2019-09-14 13:30
You can look at Tokio, but I don't how much error handling it does (it's a framework/runtime so I can imagine it leaves that up to the user). I can't really vouch for any other crates.

I don't really understand what you mean by

> Coding by copy this mistake shouldn't really be a thing.

Can you expand on that?

**Comment by cheako** [comment] 2019-09-14 15:17
@Thomasdezeeuw Taking snapshots of random projects is a recipe to clone bad code and this amplifies if everyone pertakes in this bad practice.  Even though something works and even if it compiles in Rust doesn't mean something is correct.

**Comment by Thomasdezeeuw** [comment] 2019-09-16 15:34
I think in practice most errors aren't handled (properly) only the common ones, for the remainder of the errors the connection/operation is often just restarted/retried.

**Comment by cheako** [comment] 2019-09-16 18:54
That's valid.  For a ```_ => ...``` handler in an example, a simple comment could indicate the errors typically expected on each OS and a small description of what they mean.

**Comment by Thomasdezeeuw** [comment] 2019-09-27 14:35
Closing this as error handling needs to be done per type and per OS, which is a little outside the scope of Mio.

**Closed by Thomasdezeeuw** 2019-09-27 14:35 UTC
Labels: question
