### ISSUE TITLE
Windows named pipes hits unreachable code during read operation

### ISSUE THREAD

**Issue by agneil** [tokio-rs/mio#1660] opened 2023-03-13 15:19 UTC
This is an issue we're having trouble reproducing, however, there have been instances of crashing on Windows due to the `unreachable!` line in the snippet of the `read_done` function below:

https://github.com/tokio-rs/mio/blob/9bd0e9554d7d2dbb72d17fd3587e56e2796dd83f/src/sys/windows/named_pipe.rs#L859-L863

I don't see an apparent cause, but I'm curious as to whether it could be possible the snippet below inside `scheduled_read` is returning an error that causes `mem::forget` not to be run as anticipated so the state is `Err` rather than `Pending`?

https://github.com/tokio-rs/mio/blob/9bd0e9554d7d2dbb72d17fd3587e56e2796dd83f/src/sys/windows/named_pipe.rs#L705-L709

**Comment by Thomasdezeeuw** [comment] 2024-04-08 18:11
@agneil any chance that #1772 solve this problem? The reporter of that issue is hitting the same panic as you did here.

**Comment by Thomasdezeeuw** [comment] 2024-06-09 11:59
Closing because we can't reproduce this.

@agneil if you can share code to reproduce this please do, if this an issue we still like to fix it.

**Closed by Thomasdezeeuw** 2024-06-09 11:59 UTC
