### ISSUE TITLE
mio v0.7.13 warning: dereferencing a null pointer

### ISSUE THREAD

**Issue by notdanilo** [tokio-rs/mio#1515] opened 2021-10-06 16:56 UTC
Here is the build output:
```rust
       Fresh mio v0.7.13
warning: dereferencing a null pointer
   --> C:\Users\dangu\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.13\src\sys\windows\named_pipe.rs:28:10
    |
28  |         &(*(0 as *const $t)).$($field).+ as *const _ as usize
    |          ^^^^^^^^^^^^^^^^^^^ this code causes undefined behavior when executed
...
608 |     let me = unsafe { overlapped2arc!(status.overlapped(), Inner, connect) };
    |                       ---------------------------------------------------- in this macro invocation
    |
    = note: `#[warn(deref_nullptr)]` on by default
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: dereferencing a null pointer
   --> C:\Users\dangu\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.13\src\sys\windows\named_pipe.rs:28:10
    |
28  |         &(*(0 as *const $t)).$($field).+ as *const _ as usize
    |          ^^^^^^^^^^^^^^^^^^^ this code causes undefined behavior when executed
...
634 |     let me = unsafe { overlapped2arc!(status.overlapped(), Inner, read) };
    |                       ------------------------------------------------- in this macro invocation
    |
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: dereferencing a null pointer
   --> C:\Users\dangu\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.13\src\sys\windows\named_pipe.rs:28:10
    |
28  |         &(*(0 as *const $t)).$($field).+ as *const _ as usize
    |          ^^^^^^^^^^^^^^^^^^^ this code causes undefined behavior when executed
...
666 |     let me = unsafe { overlapped2arc!(status.overlapped(), Inner, write) };
    |                       -------------------------------------------------- in this macro invocation
    |
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: 3 warnings emitted
```

**Comment by Thomasdezeeuw** [comment] 2021-10-06 18:56
Duplicate of https://github.com/tokio-rs/mio/issues/1483, should backport https://github.com/tokio-rs/mio/pull/1485.

**Comment by Thomasdezeeuw** [comment] 2021-11-06 13:33
Fixed by https://github.com/tokio-rs/mio/pull/1519.

**Closed by Thomasdezeeuw** 2021-11-06 13:33 UTC
