### ISSUE TITLE
creating Poll at high frequency on FreeBSD returns @ certain point "code: 9, kind: Other, message: \"Bad file descriptor\"

### ISSUE THREAD

**Issue by przygienda** [tokio-rs/mio#910] opened 2019-01-20 06:27 UTC
as it says. Issue does NOT happen when polls are created @ slower frequency. We're talking 4-5 polls per millisec. Vex'ing issue.

**Comment by Thomasdezeeuw** [comment] 2019-01-20 09:16
Could you share the code your ran to create this issue? And could your share a bit more detail about your FreeBSD setup?

Looking at the FreeBSD manual code 9 is `EBADF` [[1]]. And that error code should only be returned by `kevent` if you're using an invalid file descriptor [[2]].

[1]: https://www.freebsd.org/cgi/man.cgi?query=errno&sektion=2&manpath=FreeBSD+12.0-RELEASE+and+PortsRETURN_VALUES
[2]: https://www.freebsd.org/cgi/man.cgi?query=kqueue&manpath=FreeBSD+12.0-RELEASE+and+Ports#ERRORS

**Comment by przygienda** [comment] 2019-01-20 16:56
cannot share the code, FreeBSD 11. yes, I understand EBADF and it only shows under failry heavy load, let's say 10-20 Poll::new within a millisec or so. anything wrong with the system selector generation in MIO ? I saw that it's atomic with Relaxed in some parts ...

**Comment by asomers** [comment] 2019-01-20 17:10
At times like this I like to run my process in ktrace.  Can you try that?

**Comment by przygienda** [comment] 2019-01-20 17:33
ktrace will completely overrung me, I have thousands of calls going on. I'll try to ktrace kqueue, kevent & close. It's really Poll::new() which is the culprit in 95% of the cases under load.

**Comment by przygienda** [comment] 2019-01-20 17:47
sigh, difficult environ, the failing daemon is forked of another daemon that drives it to pick up the load, not sure how to plug ktrace into that. May take a while ...

**Comment by asomers** [comment] 2019-01-20 17:55
It's more work, but when ktrace just can't cut it you may be able to use dtrace instead.  For example, this command will show you the name of the syscall that's returning the error: `syscall:freebsd:*:return /errno == 9/ {trace(".");}`.

**Comment by przygienda** [comment] 2019-01-20 18:55
even more disturbingly, I see accept failures after reacting to a poll event as well sporadically with same EBADF error under reasonable load.

**Comment by asomers** [comment] 2019-01-20 18:58
What kind of failures?

**Comment by przygienda** [comment] 2019-01-20 19:01
also EBADF ...

**Comment by Thomasdezeeuw** [comment] 2019-01-21 08:06
This is going to be very hard to debug without some way for us to reproduce the errors. @przygienda Can you create a minimal reproducible example for us?

**Comment by carllerche** [comment] 2019-02-20 17:31
Mio does very little on freebsd w/ kqueue. I am not saying there is no bug, but I'm not sure where in *mio* code anything like that could live.

**Comment by asomers** [comment] 2019-02-20 17:35
@przygienda does your application set `PollOpt::oneshot`?  If so, then this might be a dupe of #911 .

**Comment by przygienda** [comment] 2019-02-20 17:44
very interesting, lemme check ...

**Comment by przygienda** [comment] 2019-02-20 17:48
nope, I don't. used to do that, I'm driving everything ::edge (and some level) now since I didn't see any benefit ...

**Comment by Thomasdezeeuw** [comment] 2019-07-08 19:49
@przygienda any update on this? I'm inclined to close this as we can't reproduce the error.

**Comment by Thomasdezeeuw** [comment] 2019-07-22 11:57
Closing due to inactivity. If someone hit this again, or can find the root cause please let us know.

**Closed by Thomasdezeeuw** 2019-07-22 11:57 UTC
