### ISSUE TITLE
Cannot compile on Windows 10

### ISSUE THREAD

**Issue by DuredhelFinceleb** [tokio-rs/mio#1537] opened 2021-12-04 00:10 UTC
Environment:
Windows 10 Pro 21H1
Rust 1.56.1, target stable-x86_64-pc-windows-msvc
test project: https://github.com/DuredhelFinceleb/embedded_files_server
mio version; 0.7.14

In this test project, mio 0.7.14 is pulled as a dependency of rocket 0.5.0-rc.1

Under Linux (including WSL), everything works fine.

Under Windows 10 Pro, it fails on mio compilation.
I'm new to Rust, this is way above my current level unfortunately
Here is the output
```
error[E0432]: unresolved import `winapi::um::ioapiset`
  --> C:\Users\vmdev\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.14\src\sys\windows\named_pipe.rs:12:17
   |
12 | use winapi::um::ioapiset::CancelIoEx;
   |                 ^^^^^^^^ could not find `ioapiset` in `um`

error[E0308]: mismatched types
   --> C:\Users\vmdev\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.14\src\sys\windows\selector.rs:514:26
    |
514 |                 callback(iocp_event.entry(), Some(events));
    |                          ^^^^^^^^^^^^^^^^^^ expected struct `OVERLAPPED_ENTRY`, found struct `windows_sys::Windows::Win32::System::IO::OVERLAPPED_ENTRY`
    |
    = note: expected reference `&OVERLAPPED_ENTRY`
               found reference `&windows_sys::Windows::Win32::System::IO::OVERLAPPED_ENTRY`

error[E0308]: mismatched types
   --> C:\Users\vmdev\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.14\src\sys\windows\selector.rs:519:46
    |
519 |             let sock_state = from_overlapped(iocp_event.overlapped());
    |                                              ^^^^^^^^^^^^^^^^^^^^^^^ expected struct `OVERLAPPED`, found struct `windows_sys::Windows::Win32::System::IO::OVERLAPPED`
    |
    = note: expected raw pointer `*mut OVERLAPPED`
               found raw pointer `*mut windows_sys::Windows::Win32::System::IO::OVERLAPPED`

error[E0308]: mismatched types
   --> C:\Users\vmdev\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.14\src\sys\windows\selector.rs:715:38
    |
715 | ...                   callback(iocp_event.entry(), None);
    |                                ^^^^^^^^^^^^^^^^^^ expected struct `OVERLAPPED_ENTRY`, found struct `windows_sys::Windows::Win32::System::IO::OVERLAPPED_ENTRY`
    |
    = note: expected reference `&OVERLAPPED_ENTRY`
               found reference `&windows_sys::Windows::Win32::System::IO::OVERLAPPED_ENTRY`

error[E0308]: mismatched types
   --> C:\Users\vmdev\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.14\src\sys\windows\selector.rs:718:63
    |
718 | ...                   let _sock_state = from_overlapped(iocp_event.overlapped());
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^^ expected struct `OVERLAPPED`, found struct `windows_sys::Windows::Win32::System::IO::OVERLAPPED`
    |
    = note: expected raw pointer `*mut OVERLAPPED`
               found raw pointer `*mut windows_sys::Windows::Win32::System::IO::OVERLAPPED`

error[E0308]: mismatched types
  --> C:\Users\vmdev\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.14\src\sys\windows\overlapped.rs:26:18
   |
25 |     pub(crate) fn as_ptr(&self) -> *const OVERLAPPED {
   |                                    ----------------- expected `*const OVERLAPPED` because of return type
26 |         unsafe { (*self.inner.get()).raw() }
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `OVERLAPPED`, found struct `windows_sys::Windows::Win32::System::IO::OVERLAPPED`
   |
   = note: expected raw pointer `*const OVERLAPPED`
              found raw pointer `*mut windows_sys::Windows::Win32::System::IO::OVERLAPPED`

error[E0308]: mismatched types
   --> C:\Users\vmdev\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.14\src\sys\windows\named_pipe.rs:634:47
    |
634 |     let status = CompletionStatus::from_entry(status);
    |                                               ^^^^^^ expected struct `windows_sys::Windows::Win32::System::IO::OVERLAPPED_ENTRY`, found struct `OVERLAPPED_ENTRY`
    |
    = note: expected reference `&windows_sys::Windows::Win32::System::IO::OVERLAPPED_ENTRY`
               found reference `&OVERLAPPED_ENTRY`

error[E0308]: mismatched types
   --> C:\Users\vmdev\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.14\src\sys\windows\named_pipe.rs:639:69
    |
639 |     let me = unsafe { Arc::from_raw(Inner::ptr_from_conn_overlapped(status.overlapped())) };
    |                                                                     ^^^^^^^^^^^^^^^^^^^ expected struct `OVERLAPPED`, found struct `windows_sys::Windows::Win32::System::IO::OVERLAPPED`  
    |
    = note: expected raw pointer `*mut OVERLAPPED`
               found raw pointer `*mut windows_sys::Windows::Win32::System::IO::OVERLAPPED`

error[E0308]: mismatched types
   --> C:\Users\vmdev\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.14\src\sys\windows\named_pipe.rs:660:47
    |
660 |     let status = CompletionStatus::from_entry(status);
    |                                               ^^^^^^ expected struct `windows_sys::Windows::Win32::System::IO::OVERLAPPED_ENTRY`, found struct `OVERLAPPED_ENTRY`
    |
    = note: expected reference `&windows_sys::Windows::Win32::System::IO::OVERLAPPED_ENTRY`
               found reference `&OVERLAPPED_ENTRY`

error[E0308]: mismatched types
   --> C:\Users\vmdev\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.14\src\sys\windows\named_pipe.rs:665:69
    |
665 |     let me = unsafe { Arc::from_raw(Inner::ptr_from_read_overlapped(status.overlapped())) };
    |                                                                     ^^^^^^^^^^^^^^^^^^^ expected struct `OVERLAPPED`, found struct `windows_sys::Windows::Win32::System::IO::OVERLAPPED`  
    |
    = note: expected raw pointer `*mut OVERLAPPED`
               found raw pointer `*mut windows_sys::Windows::Win32::System::IO::OVERLAPPED`

error[E0308]: mismatched types
   --> C:\Users\vmdev\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.14\src\sys\windows\named_pipe.rs:692:47
    |
692 |     let status = CompletionStatus::from_entry(status);
    |                                               ^^^^^^ expected struct `windows_sys::Windows::Win32::System::IO::OVERLAPPED_ENTRY`, found struct `OVERLAPPED_ENTRY`
    |
    = note: expected reference `&windows_sys::Windows::Win32::System::IO::OVERLAPPED_ENTRY`
               found reference `&OVERLAPPED_ENTRY`

error[E0308]: mismatched types
   --> C:\Users\vmdev\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.14\src\sys\windows\named_pipe.rs:697:70
    |
697 |     let me = unsafe { Arc::from_raw(Inner::ptr_from_write_overlapped(status.overlapped())) };
    |                                                                      ^^^^^^^^^^^^^^^^^^^ expected struct `OVERLAPPED`, found struct `windows_sys::Windows::Win32::System::IO::OVERLAPPED` 
    |
    = note: expected raw pointer `*mut OVERLAPPED`
               found raw pointer `*mut windows_sys::Windows::Win32::System::IO::OVERLAPPED`
```

In the Cargo.lock I see that winapi is present
```
[[package]]
name = "winapi"
version = "0.3.9"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "5c839a674fcd7a98952e593242ea400abe93992746761e38641405d28b00f419"
dependencies = [
 "winapi-i686-pc-windows-gnu",
 "winapi-x86_64-pc-windows-gnu",
]
```
And I can see the dependency of mio on winapi is there too
```
[[package]]
name = "mio"
version = "0.7.14"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "8067b404fe97c70829f082dec8bcf4f71225d7eaea1d8645349cb76fa06205cc"
dependencies = [
 "libc",
 "log",
 "miow",
 "ntapi",
 "winapi",
]
```
I do not understand what is happening here. Can someone help?

**Comment by Darksonn** [comment] 2021-12-04 10:30
Seems to be duplicate of #1535.

**Comment by Thomasdezeeuw** [comment] 2021-12-04 11:02
> Seems to be duplicate of #1535.

Correct.

@DuredhelFinceleb If you run `cargo update` it should downgrade to miow 0.3.7 (note the *w*) which doesn't contain the breaking change.

**Closed by Thomasdezeeuw** 2021-12-04 11:02 UTC

**Comment by DuredhelFinceleb** [comment] 2021-12-05 18:40
It works! Thanks a lot!
