### ISSUE TITLE
Windows TCP implementation hits unreachable code

### ISSUE THREAD

**Issue by rbtying** [tokio-rs/mio#921] opened 2019-03-21 06:04 UTC
We've noticed that sometimes (very, very rarely), we get crashes on Windows which are caused by this `unreachable!` statement here:

https://github.com/carllerche/mio/blob/master/src/sys/windows/tcp.rs#L571

It's nonobvious to me why we would ever end up in there, but immediately prior to that we have some logs which reference WSAECONNRESET -- is there a possibility that in the connection reset case that the mio implementation will incorrectly enter `write_done` ?

Edit (by @Thomasdezeeuw):
fixed link to the unreachable statement: https://github.com/tokio-rs/mio/blob/ab099cb5e150c16ceac1654f2c8ed5bcb094fb29/src/sys/windows/tcp.rs#L568.

**Comment by carllerche** [comment] 2019-04-02 18:12
Sorry for the delay. Hitting that code path indicates a bug. It has
been a long time since I worked in that part of the code and nothing
stands out. At this point, the windows implementation is due for a
rewrite (https://github.com/tokio-rs/gsoc/issues/3), so I probably
won't be able to spend time debugging this. If you discover the issue,
I would be happy to accept a PR & release.

Cheers,
Carl

**Comment by FXTi** [comment] 2019-04-09 03:45
@rbtying Would you reproduce the crush case or provide the test case?

More information is definitely needed for clarify the situation here, since the crashes is very rare.

**Comment by rbtying** [comment] 2019-04-09 03:48
@FXTi @carllerche thanks for the responses! I'm trying to narrow down the crash conditions, but this is coming from a fairly complicated app and we have pretty limited telemetry. I'll let you know if I can get a repro!

**Comment by Thomasdezeeuw** [comment] 2019-06-02 14:31
@rbtying Any update on this?

**Comment by rbtying** [comment] 2019-06-02 14:33
I honestly haven't had time to dig into this more -- mostly, we don't have
a clean lab repro, but we have panic stacks that point here. Unfortunately
gotten busy with other stuff, though.

**Comment by bgianfo** [comment] 2019-06-04 00:53
@rbtying Do you have a crash dump? If you do can you determine what the state is, if it's not pending? It seems like possibly IO cancellation might be involved here.

You could try writing to a connection and closing it on the remote side in a loop?

**Comment by Thomasdezeeuw** [comment] 2019-07-20 14:17
The Windows implementation is rewritten, so I'm closing this, too bad we didn't find the root cause.

**Closed by Thomasdezeeuw** 2019-07-20 14:17 UTC
Labels: windows
